### PR TITLE
Add support for event reader

### PR DESCRIPTION
**Pull request by fritzmg**
Currently the extension collects images from events only via the `getAllEvents` hook. However, that hooks isn't actually executed on the detail page of an event. Thus there will be no `og:image` URL of an event.

This PR implements support for the event reader image by implementing a `getContentElement` hook. The hook checks whether this is the event detail page via various variables, i.e. the presence of an item and whether the content element is a module content element that includes either a event reader module directly or an event list module with a reader module defined.

### CODE REVIEW

**Comment by qzminski** [comment]
Do I assume correctly that if the event reader module is included via page layout, then this hook will not work? 

I wonder if we could perhaps use the `parseTemplate` hook and check if template starts with `mod_eventreader`… what do you think?

**Comment by fritzmg** [comment]
An eventreader in the layout probably never makes sense, but I agree, using the parseTemplate hook is the better approach. I will update the PR accordingly.

**Comment by qzminski** [comment]
I assume it's tested and I can merge it already?

**Comment by fritzmg** [comment]
Yes :)

**Comment by qzminski** [comment]
Released in 3.6.0, thank you @fritzmg !

**Pull request merged**
