### PR TITLE
Allow definition of specific social image for news and events

### PR DESCRIPTION
**Pull request by fritzmg**
Our customers often want to define a specific image for sharing on social networks that is different from the teaser image of the news or event (as it might be a different image altogether or include additional text etc.).

This PR allows to set a specific social image for news and events which will then be used instead of the teaser image.

Polish and Italian translation missing though.

### CODE REVIEW

**Review by qzminski — CHANGES_REQUESTED** [review]
Looks good, but can we just use the `PaletteManipulator` for palettes instead of `str_replace`? I will bump the dependencies if needed.

**Comment by fritzmg** [comment]
Yeah, I only did not use it since this extension is still requiring `"contao/core-bundle": "~3.2 || ~4.0"`. If we change that to `"contao/core-bundle": "^4.4"` I can change it to use the PaletteManipulator.

**Comment by qzminski** [comment]
Can you include that dependency bump in your PR please?

**Comment by fritzmg** [comment]
Done :)

**Comment by qzminski** [comment]
Just released as 3.7.0, thank you @fritzmg !

**Pull request merged**
